### ISSUE TITLE
Do not allow to deleted the connected user

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#104]

**Comment by YankevinPlacali** [comment]
@MentalistHB I think that this ticket should be for the backend. In backend we can compare the actual Session user id with the id to be delete and block the delete operation

**Comment by Chombon** [comment]
The backend does not work with the session id.

**Comment by Chombon** [comment]
State: Adapt the implementation according to the new specification: 2 h

**Comment by MentalistHB** [comment]
@Chombon in the class `com.ambacam.service.TokenService` there is a method called `getConnectedOperateur(HttpServletRequest request)` ready to be used. You could use it to get the connected `Operateur`. To do so, simply take the `HttpServletRequest` in the header of the resource and then inject the `TokenService` in the service where you want to use it.
