### ISSUE TITLE
Implement requete groupe

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#106]
Take into account the description in #72

**Comment by wakeugit** [comment]
@MentalistHB @Chombon Please take a look at this endpoints. I always become a Bad request error

- /operateurs/{operateurId}/requete-groupes/{requeteGroupeId}/requetes/status
- /operateurs/{operateurId}/requete-groupes/{requeteGroupeId}/status

Thank you
