### ISSUE TITLE
Creer des instances amazons

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#12]

**Comment by Coccoonx** [comment]
Est-ce nécessaire de créer des instances Amazon à ce stade ?
Aucun code n'a encore été écrit. Il n'y a encore rien à deployer. 
Je le dis parce Amazon est coûteux. Et s'il faut profiter des 12 mois de gratuité, autant mieux lancer cela lorsqu'on a déjà une version à déployer.
Par ailleurs, j'ai des raisons de penser des alternatives comme Heroku ou encore Google Firebase sont moins coûteuse.

**Comment by MentalistHB** [comment]
Avec Amazon, nous disposons bien evidemment de service free tier qui sont gratuits. Ils nous serviront a avoir nos servers dev et test. Ceci pourrai s'averer egalement utile pour le font-end et nous permettra aussi de centraliser le travail.
