### ISSUE TITLE
Implementer les endpoints de l'objet Action

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#24]
Implementer les endpoints CRUD de l'objet Action.

Une fonctionnalite similaire a ete implemente dans #19

**Comment by Coccoonx** [comment]
Starting

**Comment by Coccoonx** [comment]
Waiting reviewers

**Comment by MentalistHB** [comment]
@Coccoonx Why did you not create this branch based on the master? The same applies for the branch about Autorities

**Comment by MentalistHB** [comment]
![screenshot from 2018-06-16 20-50-45](https://user-images.githubusercontent.com/23260207/41501553-fb8a522a-71a6-11e8-8e24-1bed2c95e9b5.png)
