### ISSUE TITLE
Implement endpoint Operateur Requerant Requetes

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#42]
Implement endpoint Requerant Requete (/requetes, /operateurs/{operateurId}/requerants/{requerantId}/requetes, /operateurs/{operateurId}/requerants/{requerantId}/requetes/{requeteId}, /operateurs/{operateurId}/requerants/{requerantId}/requetes/{requeteId}/status)

Needs #40 and #41 to be implemented

**Comment by Chombon** [comment]
@MentalistHB I have some questions:
- operateur and status can be null?
- if no, how should they be set in the create requete?
