### ISSUE TITLE
Create endpoint Recepisse

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#54]
Create endpoint Recepisse:

GET, PUT, POST and DELETE /requerants/{requerantId}/requetes/{requeteId}/recepisses

This issue might depend on #42

**Comment by Coccoonx** [comment]
starting

**Comment by Coccoonx** [comment]
Hey @MentalistHB I have some concerns:
1 - Where does a Recepisse is involved in the flow of our program ? I'm browsing available APIs in swagger but I'm not seeing how Recepisse is used.
2 - I need more information about packaging of Recepisse. I don't know where to put rest apis and I will appreciate if you explain me a second time the logic behind sub-folders in rest package.

**Comment by MentalistHB** [comment]
@Coccoonx As the urls say, a Requete might have many Recepisse. This means that there is OneToMany relationship between Requete and Recepisse. For more details, you can take a look at the class diagram which is in the "Specifications techniques.docx" in OneDrive. Therefore, the class Recepisse contains an attribute requete which is @ManyToOne. In My conception, I left it firstly like this instead of having @OneToOne for a generic purpose.

There was indeed a little mistake in the Swagger. Instead of the requete attribute in Recepisse, there was requerant. I've already changed it.

The packaging should reflect the url. For instance: here we have the url `/requerants/{requerantId}/requetes/{requeteId}/recepisses`. This means, we should have the following packages: .../rest/requerants/requetes/recepisses.

We implement it first this way. It could change once we will implement the authentication with tokens and authorizations.

This could be an interesting topic for @Chombon and @MistraForest too.

**Comment by Coccoonx** [comment]
Thanks
