### ISSUE TITLE
Implement option Requerant

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#67]

**Comment by MentalistHB** [comment]
@gancia-kiss You can start with this issue.
Please consider the template which is given by the feature Role already implemented.

**Be aware**:
There is a readme file in the folder `frontend`. On the bottom of this file, you will find a link to the full preview of our template which is of course open source. Feel free to take a look at it if you look for inspiration regarding a particular component.

**Remember**:

- One issue => one branch
- Name of the branch: [issueNumber]-[issueNameSpacesReplacedBy-]

Don't hesitate to ask if you have questions

I wish you success!!!

**Comment by Coccoonx** [comment]
Summary:
  - clonage of git repo
  - starting implementation of Requerant feature

Problem:
  - I'm not able to launch the backend app to test.

Next Steps:
 - Fix the backend issue and completing the implementation of Requerant

**Comment by wakeugit** [comment]
Summary:

- generate different component (form and table)
- create models
- create services
- create table and form (modal)

Problem:

bad request

Next Steps:

adapt the model to build a good request (2 h)
finalize the implementation of this component (4 h)
