### ISSUE TITLE
Implement requete

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#72]
The link requetes should be implemented in the same was as the link role.

Instead of having a under requetes the options Nouvelle requete and liste, it should be structured as following:

-Requetes
    - Toutes les requetes
    - Groupes

Only the option groupes should be developed. This should implement the endpoint requeteGroup from the Swagger Specs.

Please, take a look at that

**Comment by wakeugit** [comment]
Summary:
- clonage of git repo
- Starting implementation of Requete feature
- Generate component to manage "Requetes" 
- Generate component to manage "RequetesForm" 
- Insert  menu options on the left side and add the routes 

Problem:
Not able to start the backend, to see the attributes of tables and build models on frontend side

Next Steps:
- Implement the form for adding new request (3 h)
- Save the Requete-Infos in the database (6 h)
- Update the table showing the all "Requetes" (4 h)

**Comment by wakeugit** [comment]
Summary:

- Implement the form for "requete". this form require Components "Type requete" and "Requerant"
- add buttons and modals to add a "Type Requete" and "Requerant", if not existing in the combo-box

Problem:

- The implementation of this issue depend from many others like "Requerant" and "Type Requete". So it is necessary to finish it before continuing with the implementation of this issue. 

Next Steps:

- Create Issue "implement Type Requete" and implement it (4 h)
- Continue implement requete, if implement requerant is finished
     - Save the Requete-Infos in the database (6 h)
     - Update the table showing the all "Requetes" (4 h)

**Comment by wakeugit** [comment]
Summary:

- the implementation of this ticket is finish

Problem:

- nothing

Next Steps:

- in review
