### ISSUE TITLE
Diagramme de paquetage frontend

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#9]
Etablir un diagramme de paquet du projet fontend contenant les dispositions pour:

- les services
- les modeles
- les composants
- les outils
- les configurations
- ...

**Comment by MentalistHB** [comment]
Etablir un diagramme de paquet du projet fontend contenant les dispositions pour:

- les services
- les modeles
- les composants
- les outils
- ...

**Comment by Coccoonx** [comment]
[Diagramme de paquetage front end.pdf](https://github.com/YankevinPlacali/Ambacam2018/files/2065870/Diagramme.de.paquetage.front.end.pdf)
Première version du diagramme de paquetage

**Comment by Coccoonx** [comment]
Je suggère aux curieux de jeter un oeil sur ce lien.
https://medium.com/@cyrilletuzi/architecture-in-angular-projects-242606567e40
Il présente l'architecture d'un projet Angular appelé à devenir robuste.
Perso, je suis familié avec celle que j'ai proposé.

**Comment by MentalistHB** [comment]
Deja fait. Ce n'etait pas grand chose
