### ISSUE TITLE
Implement the interfaces for StatusRequete

### ISSUE THREAD

**Issue by MentalistHB** [YankevinPlacali/Ambacam2018#92]
Use role as model

**Comment by YankevinPlacali** [comment]
The request doens't work.. Authentication problem
![auth](https://user-images.githubusercontent.com/21308042/46998905-44e9c900-d124-11e8-8278-9df6db84e57f.png)

**Comment by YankevinPlacali** [comment]
@MentalistHB can you please take a look at this ticket? I though that it was already close. I recently did a commit. I found that the "create" button in the List of Status is not working. I did the same changes as inthe branch 94 but still the same.

**Comment by MentalistHB** [comment]
The changes were not exactly the same.

From today, please the feature action as reference

**Comment by MentalistHB** [comment]
@YankevinPlacali No pull request was created for this issue
